[2023-07-28 18:52:43,262] {scheduler_job.py:182} INFO - Started process (PID=43) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:52:43,277] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:52:43,280] {logging_mixin.py:104} INFO - [2023-07-28 18:52:43,279] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:52:43,316] {logging_mixin.py:104} INFO - [2023-07-28 18:52:43,306] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:52:43,319] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:52:43,345] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.087 seconds
[2023-07-28 18:53:13,467] {scheduler_job.py:182} INFO - Started process (PID=50) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:53:13,478] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:53:13,480] {logging_mixin.py:104} INFO - [2023-07-28 18:53:13,480] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:53:13,495] {logging_mixin.py:104} INFO - [2023-07-28 18:53:13,493] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:53:13,498] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:53:13,517] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.055 seconds
[2023-07-28 18:53:43,626] {scheduler_job.py:182} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:53:43,628] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:53:43,630] {logging_mixin.py:104} INFO - [2023-07-28 18:53:43,630] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:53:43,642] {logging_mixin.py:104} INFO - [2023-07-28 18:53:43,640] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:53:43,644] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:53:43,661] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.038 seconds
[2023-07-28 18:54:13,788] {scheduler_job.py:182} INFO - Started process (PID=54) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:54:13,791] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:54:13,793] {logging_mixin.py:104} INFO - [2023-07-28 18:54:13,792] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:54:13,809] {logging_mixin.py:104} INFO - [2023-07-28 18:54:13,806] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:54:13,812] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:54:13,832] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.049 seconds
[2023-07-28 18:54:43,959] {scheduler_job.py:182} INFO - Started process (PID=56) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:54:43,962] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:54:43,963] {logging_mixin.py:104} INFO - [2023-07-28 18:54:43,963] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:54:43,979] {logging_mixin.py:104} INFO - [2023-07-28 18:54:43,977] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:54:43,982] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:54:44,002] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 18:55:14,124] {scheduler_job.py:182} INFO - Started process (PID=58) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:55:14,127] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:55:14,129] {logging_mixin.py:104} INFO - [2023-07-28 18:55:14,129] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:55:14,144] {logging_mixin.py:104} INFO - [2023-07-28 18:55:14,142] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:55:14,147] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:55:14,177] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.057 seconds
[2023-07-28 18:55:44,331] {scheduler_job.py:182} INFO - Started process (PID=60) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:55:44,334] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:55:44,336] {logging_mixin.py:104} INFO - [2023-07-28 18:55:44,336] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:55:44,351] {logging_mixin.py:104} INFO - [2023-07-28 18:55:44,349] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:55:44,353] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:55:44,375] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 18:56:14,516] {scheduler_job.py:182} INFO - Started process (PID=62) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:56:14,518] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:56:14,520] {logging_mixin.py:104} INFO - [2023-07-28 18:56:14,519] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:56:14,535] {logging_mixin.py:104} INFO - [2023-07-28 18:56:14,533] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:56:14,538] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:56:14,557] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 18:56:44,714] {scheduler_job.py:182} INFO - Started process (PID=64) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:56:44,717] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:56:44,718] {logging_mixin.py:104} INFO - [2023-07-28 18:56:44,718] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:56:44,736] {logging_mixin.py:104} INFO - [2023-07-28 18:56:44,734] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:56:44,738] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:56:44,759] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 18:57:14,908] {scheduler_job.py:182} INFO - Started process (PID=66) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:57:14,910] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:57:14,913] {logging_mixin.py:104} INFO - [2023-07-28 18:57:14,913] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:57:14,928] {logging_mixin.py:104} INFO - [2023-07-28 18:57:14,926] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:57:14,930] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:57:14,948] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.044 seconds
[2023-07-28 18:57:45,113] {scheduler_job.py:182} INFO - Started process (PID=68) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:57:45,115] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:57:45,117] {logging_mixin.py:104} INFO - [2023-07-28 18:57:45,117] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:57:45,132] {logging_mixin.py:104} INFO - [2023-07-28 18:57:45,129] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:57:45,134] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:57:45,152] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.043 seconds
[2023-07-28 18:58:15,298] {scheduler_job.py:182} INFO - Started process (PID=70) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:58:15,302] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:58:15,304] {logging_mixin.py:104} INFO - [2023-07-28 18:58:15,304] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:58:15,320] {logging_mixin.py:104} INFO - [2023-07-28 18:58:15,318] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:58:15,322] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:58:15,343] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 18:58:45,585] {scheduler_job.py:182} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:58:45,588] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:58:45,591] {logging_mixin.py:104} INFO - [2023-07-28 18:58:45,591] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:58:45,610] {logging_mixin.py:104} INFO - [2023-07-28 18:58:45,608] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:58:45,613] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:58:45,633] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.054 seconds
[2023-07-28 18:59:15,777] {scheduler_job.py:182} INFO - Started process (PID=74) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:59:15,780] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:59:15,781] {logging_mixin.py:104} INFO - [2023-07-28 18:59:15,781] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:59:15,797] {logging_mixin.py:104} INFO - [2023-07-28 18:59:15,794] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:59:15,799] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:59:15,819] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 18:59:46,001] {scheduler_job.py:182} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:59:46,004] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 18:59:46,006] {logging_mixin.py:104} INFO - [2023-07-28 18:59:46,006] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:59:46,022] {logging_mixin.py:104} INFO - [2023-07-28 18:59:46,020] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 18:59:46,025] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 18:59:46,045] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.049 seconds
[2023-07-28 19:00:16,185] {scheduler_job.py:182} INFO - Started process (PID=78) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:00:16,188] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:00:16,190] {logging_mixin.py:104} INFO - [2023-07-28 19:00:16,190] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:00:16,208] {logging_mixin.py:104} INFO - [2023-07-28 19:00:16,206] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import flight_extraction
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 19:00:16,212] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:00:16,234] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.054 seconds
[2023-07-28 19:00:37,359] {scheduler_job.py:182} INFO - Started process (PID=80) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:00:37,366] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:00:37,370] {logging_mixin.py:104} INFO - [2023-07-28 19:00:37,370] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:00:37,439] {logging_mixin.py:104} INFO - [2023-07-28 19:00:37,434] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:00:37,446] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:00:37,503] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.157 seconds
[2023-07-28 19:01:07,606] {scheduler_job.py:182} INFO - Started process (PID=82) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:01:07,610] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:01:07,612] {logging_mixin.py:104} INFO - [2023-07-28 19:01:07,612] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:01:07,629] {logging_mixin.py:104} INFO - [2023-07-28 19:01:07,627] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:01:07,632] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:01:07,652] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.051 seconds
[2023-07-28 19:01:37,767] {scheduler_job.py:182} INFO - Started process (PID=84) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:01:37,769] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:01:37,771] {logging_mixin.py:104} INFO - [2023-07-28 19:01:37,771] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:01:37,788] {logging_mixin.py:104} INFO - [2023-07-28 19:01:37,786] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:01:37,790] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:01:37,811] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:02:07,928] {scheduler_job.py:182} INFO - Started process (PID=86) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:02:07,931] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:02:07,933] {logging_mixin.py:104} INFO - [2023-07-28 19:02:07,932] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:02:07,946] {logging_mixin.py:104} INFO - [2023-07-28 19:02:07,944] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:02:07,948] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:02:07,966] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.042 seconds
[2023-07-28 19:02:38,087] {scheduler_job.py:182} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:02:38,090] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:02:38,092] {logging_mixin.py:104} INFO - [2023-07-28 19:02:38,092] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:02:38,107] {logging_mixin.py:104} INFO - [2023-07-28 19:02:38,105] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:02:38,109] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:02:38,129] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 19:03:08,230] {scheduler_job.py:182} INFO - Started process (PID=90) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:03:08,233] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:03:08,235] {logging_mixin.py:104} INFO - [2023-07-28 19:03:08,234] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:03:08,251] {logging_mixin.py:104} INFO - [2023-07-28 19:03:08,249] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:03:08,254] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:03:08,274] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:03:38,390] {scheduler_job.py:182} INFO - Started process (PID=92) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:03:38,393] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:03:38,395] {logging_mixin.py:104} INFO - [2023-07-28 19:03:38,394] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:03:38,410] {logging_mixin.py:104} INFO - [2023-07-28 19:03:38,408] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:03:38,413] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:03:38,434] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 19:04:08,559] {scheduler_job.py:182} INFO - Started process (PID=94) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:04:08,562] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:04:08,564] {logging_mixin.py:104} INFO - [2023-07-28 19:04:08,564] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:04:08,579] {logging_mixin.py:104} INFO - [2023-07-28 19:04:08,577] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:04:08,582] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:04:08,603] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.049 seconds
[2023-07-28 19:04:38,725] {scheduler_job.py:182} INFO - Started process (PID=96) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:04:38,727] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:04:38,729] {logging_mixin.py:104} INFO - [2023-07-28 19:04:38,729] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:04:38,745] {logging_mixin.py:104} INFO - [2023-07-28 19:04:38,743] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:04:38,747] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:04:38,765] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.045 seconds
[2023-07-28 19:05:08,897] {scheduler_job.py:182} INFO - Started process (PID=98) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:05:08,900] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:05:08,903] {logging_mixin.py:104} INFO - [2023-07-28 19:05:08,903] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:05:08,923] {logging_mixin.py:104} INFO - [2023-07-28 19:05:08,921] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:05:08,927] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:05:08,952] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.060 seconds
[2023-07-28 19:05:39,088] {scheduler_job.py:182} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:05:39,091] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:05:39,093] {logging_mixin.py:104} INFO - [2023-07-28 19:05:39,092] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:05:39,108] {logging_mixin.py:104} INFO - [2023-07-28 19:05:39,106] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:05:39,111] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:05:39,130] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 19:06:09,252] {scheduler_job.py:182} INFO - Started process (PID=102) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:06:09,255] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:06:09,257] {logging_mixin.py:104} INFO - [2023-07-28 19:06:09,257] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:06:09,274] {logging_mixin.py:104} INFO - [2023-07-28 19:06:09,272] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:06:09,276] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:06:09,296] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.049 seconds
[2023-07-28 19:06:39,436] {scheduler_job.py:182} INFO - Started process (PID=104) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:06:39,439] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:06:39,441] {logging_mixin.py:104} INFO - [2023-07-28 19:06:39,441] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:06:39,458] {logging_mixin.py:104} INFO - [2023-07-28 19:06:39,456] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:06:39,461] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:06:39,483] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.052 seconds
[2023-07-28 19:07:09,625] {scheduler_job.py:182} INFO - Started process (PID=106) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:07:09,628] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:07:09,631] {logging_mixin.py:104} INFO - [2023-07-28 19:07:09,630] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:07:09,647] {logging_mixin.py:104} INFO - [2023-07-28 19:07:09,644] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:07:09,650] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:07:09,671] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.051 seconds
[2023-07-28 19:07:39,789] {scheduler_job.py:182} INFO - Started process (PID=108) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:07:39,792] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:07:39,793] {logging_mixin.py:104} INFO - [2023-07-28 19:07:39,793] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:07:39,812] {logging_mixin.py:104} INFO - [2023-07-28 19:07:39,809] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:07:39,814] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:07:39,837] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.053 seconds
[2023-07-28 19:08:09,953] {scheduler_job.py:182} INFO - Started process (PID=110) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:08:09,956] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:08:09,958] {logging_mixin.py:104} INFO - [2023-07-28 19:08:09,958] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:08:09,974] {logging_mixin.py:104} INFO - [2023-07-28 19:08:09,972] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    import airflow.flight_extraction
ModuleNotFoundError: No module named 'airflow.flight_extraction'
[2023-07-28 19:08:09,977] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:08:09,997] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.049 seconds
[2023-07-28 19:08:12,965] {scheduler_job.py:182} INFO - Started process (PID=111) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:08:12,968] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:08:12,970] {logging_mixin.py:104} INFO - [2023-07-28 19:08:12,970] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:08:12,997] {logging_mixin.py:104} INFO - [2023-07-28 19:08:12,995] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'fct_script'
[2023-07-28 19:08:13,000] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:08:13,022] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.061 seconds
[2023-07-28 19:08:43,149] {scheduler_job.py:182} INFO - Started process (PID=113) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:08:43,152] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:08:43,154] {logging_mixin.py:104} INFO - [2023-07-28 19:08:43,153] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:08:43,172] {logging_mixin.py:104} INFO - [2023-07-28 19:08:43,170] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'fct_script'
[2023-07-28 19:08:43,175] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:08:43,195] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.052 seconds
[2023-07-28 19:09:13,318] {scheduler_job.py:182} INFO - Started process (PID=115) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:09:13,320] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:09:13,322] {logging_mixin.py:104} INFO - [2023-07-28 19:09:13,322] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:09:13,340] {logging_mixin.py:104} INFO - [2023-07-28 19:09:13,337] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'fct_script'
[2023-07-28 19:09:13,342] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:09:13,362] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.049 seconds
[2023-07-28 19:09:43,494] {scheduler_job.py:182} INFO - Started process (PID=117) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:09:43,496] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:09:43,498] {logging_mixin.py:104} INFO - [2023-07-28 19:09:43,498] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:09:43,513] {logging_mixin.py:104} INFO - [2023-07-28 19:09:43,511] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'fct_script'
[2023-07-28 19:09:43,516] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:09:43,537] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:10:13,649] {scheduler_job.py:182} INFO - Started process (PID=119) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:10:13,651] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:10:13,653] {logging_mixin.py:104} INFO - [2023-07-28 19:10:13,653] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:10:13,669] {logging_mixin.py:104} INFO - [2023-07-28 19:10:13,667] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'fct_script'
[2023-07-28 19:10:13,671] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:10:13,694] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 19:10:43,816] {scheduler_job.py:182} INFO - Started process (PID=121) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:10:43,819] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:10:43,821] {logging_mixin.py:104} INFO - [2023-07-28 19:10:43,821] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:10:43,840] {logging_mixin.py:104} INFO - [2023-07-28 19:10:43,838] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'fct_script'
[2023-07-28 19:10:43,843] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:10:43,865] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.053 seconds
[2023-07-28 19:11:13,987] {scheduler_job.py:182} INFO - Started process (PID=123) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:11:13,990] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:11:13,993] {logging_mixin.py:104} INFO - [2023-07-28 19:11:13,992] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:11:14,014] {logging_mixin.py:104} INFO - [2023-07-28 19:11:14,011] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'fct_script'
[2023-07-28 19:11:14,017] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:11:14,042] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.061 seconds
[2023-07-28 19:11:44,159] {scheduler_job.py:182} INFO - Started process (PID=125) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:11:44,161] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:11:44,163] {logging_mixin.py:104} INFO - [2023-07-28 19:11:44,163] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:11:44,181] {logging_mixin.py:104} INFO - [2023-07-28 19:11:44,179] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'fct_script'
[2023-07-28 19:11:44,184] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:11:44,204] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 19:12:14,349] {scheduler_job.py:182} INFO - Started process (PID=127) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:14,352] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:12:14,354] {logging_mixin.py:104} INFO - [2023-07-28 19:12:14,354] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:14,375] {logging_mixin.py:104} INFO - [2023-07-28 19:12:14,373] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'fct_script'
[2023-07-28 19:12:14,378] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:14,402] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.059 seconds
[2023-07-28 19:12:22,379] {scheduler_job.py:182} INFO - Started process (PID=128) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:22,381] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:12:22,383] {logging_mixin.py:104} INFO - [2023-07-28 19:12:22,383] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:22,411] {logging_mixin.py:104} INFO - [2023-07-28 19:12:22,408] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from airflow.fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'airflow.fct_script'
[2023-07-28 19:12:22,414] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:22,436] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.062 seconds
[2023-07-28 19:12:52,599] {scheduler_job.py:182} INFO - Started process (PID=130) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:52,605] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:12:52,608] {logging_mixin.py:104} INFO - [2023-07-28 19:12:52,608] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:52,625] {logging_mixin.py:104} INFO - [2023-07-28 19:12:52,623] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from airflow.fct_script.flight_extraction import get_schedule
ModuleNotFoundError: No module named 'airflow.fct_script'
[2023-07-28 19:12:52,629] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:52,652] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.059 seconds
[2023-07-28 19:12:55,622] {scheduler_job.py:182} INFO - Started process (PID=131) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:55,628] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:12:55,630] {logging_mixin.py:104} INFO - [2023-07-28 19:12:55,629] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:55,654] {logging_mixin.py:104} INFO - [2023-07-28 19:12:55,652] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from flight_extraction import get_schedule
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 19:12:55,657] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:12:55,675] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.057 seconds
[2023-07-28 19:13:25,807] {scheduler_job.py:182} INFO - Started process (PID=133) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:13:25,809] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:13:25,811] {logging_mixin.py:104} INFO - [2023-07-28 19:13:25,811] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:13:25,830] {logging_mixin.py:104} INFO - [2023-07-28 19:13:25,828] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5, in <module>
    from flight_extraction import get_schedule
ModuleNotFoundError: No module named 'flight_extraction'
[2023-07-28 19:13:25,832] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:13:25,854] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.052 seconds
[2023-07-28 19:13:29,894] {scheduler_job.py:182} INFO - Started process (PID=135) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:13:29,896] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:13:29,899] {logging_mixin.py:104} INFO - [2023-07-28 19:13:29,899] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:13:29,910] {logging_mixin.py:104} INFO - [2023-07-28 19:13:29,909] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5
    from airflow/fct_script/Authentication_key_retrieval.py import get_schedule
                ^
SyntaxError: invalid syntax
[2023-07-28 19:13:29,912] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:13:29,931] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.042 seconds
[2023-07-28 19:14:00,041] {scheduler_job.py:182} INFO - Started process (PID=137) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:14:00,045] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:14:00,047] {logging_mixin.py:104} INFO - [2023-07-28 19:14:00,047] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:14:00,059] {logging_mixin.py:104} INFO - [2023-07-28 19:14:00,057] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5
    from airflow/fct_script/Authentication_key_retrieval.py import get_schedule
                ^
SyntaxError: invalid syntax
[2023-07-28 19:14:00,062] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:14:00,086] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 19:14:30,170] {scheduler_job.py:182} INFO - Started process (PID=139) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:14:30,172] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:14:30,174] {logging_mixin.py:104} INFO - [2023-07-28 19:14:30,174] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:14:30,183] {logging_mixin.py:104} INFO - [2023-07-28 19:14:30,181] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5
    from airflow/fct_script/Authentication_key_retrieval.py import get_schedule
                ^
SyntaxError: invalid syntax
[2023-07-28 19:14:30,185] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:14:30,207] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.042 seconds
[2023-07-28 19:15:00,308] {scheduler_job.py:182} INFO - Started process (PID=141) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:15:00,311] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:15:00,312] {logging_mixin.py:104} INFO - [2023-07-28 19:15:00,312] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:15:00,321] {logging_mixin.py:104} INFO - [2023-07-28 19:15:00,320] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5
    from airflow/fct_script/Authentication_key_retrieval.py import get_schedule
                ^
SyntaxError: invalid syntax
[2023-07-28 19:15:00,323] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:15:00,346] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.044 seconds
[2023-07-28 19:15:30,443] {scheduler_job.py:182} INFO - Started process (PID=143) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:15:30,446] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:15:30,448] {logging_mixin.py:104} INFO - [2023-07-28 19:15:30,448] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:15:30,457] {logging_mixin.py:104} INFO - [2023-07-28 19:15:30,456] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5
    from airflow/fct_script/Authentication_key_retrieval.py import get_schedule
                ^
SyntaxError: invalid syntax
[2023-07-28 19:15:30,460] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:15:30,481] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.044 seconds
[2023-07-28 19:16:00,560] {scheduler_job.py:182} INFO - Started process (PID=145) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:16:00,564] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:16:00,566] {logging_mixin.py:104} INFO - [2023-07-28 19:16:00,566] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:16:00,574] {logging_mixin.py:104} INFO - [2023-07-28 19:16:00,573] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5
    from airflow/fct_script/Authentication_key_retrieval.py import get_schedule
                ^
SyntaxError: invalid syntax
[2023-07-28 19:16:00,577] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:16:00,598] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.042 seconds
[2023-07-28 19:16:30,698] {scheduler_job.py:182} INFO - Started process (PID=146) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:16:30,701] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:16:30,703] {logging_mixin.py:104} INFO - [2023-07-28 19:16:30,702] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:16:30,713] {logging_mixin.py:104} INFO - [2023-07-28 19:16:30,712] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5
    from airflow/fct_script/Authentication_key_retrieval.py import get_schedule
                ^
SyntaxError: invalid syntax
[2023-07-28 19:16:30,715] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:16:30,740] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:17:00,881] {scheduler_job.py:182} INFO - Started process (PID=148) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:17:00,883] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:17:00,885] {logging_mixin.py:104} INFO - [2023-07-28 19:17:00,885] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:17:00,895] {logging_mixin.py:104} INFO - [2023-07-28 19:17:00,894] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5
    from airflow/fct_script/Authentication_key_retrieval.py import get_schedule
                ^
SyntaxError: invalid syntax
[2023-07-28 19:17:00,897] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:17:00,920] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.045 seconds
[2023-07-28 19:17:31,068] {scheduler_job.py:182} INFO - Started process (PID=150) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:17:31,071] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:17:31,073] {logging_mixin.py:104} INFO - [2023-07-28 19:17:31,072] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:17:31,082] {logging_mixin.py:104} INFO - [2023-07-28 19:17:31,081] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5
    from airflow/fct_script/Authentication_key_retrieval.py import get_schedule
                ^
SyntaxError: invalid syntax
[2023-07-28 19:17:31,084] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:17:31,107] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.043 seconds
[2023-07-28 19:18:01,271] {scheduler_job.py:182} INFO - Started process (PID=152) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:18:01,273] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:18:01,275] {logging_mixin.py:104} INFO - [2023-07-28 19:18:01,275] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:18:01,283] {logging_mixin.py:104} INFO - [2023-07-28 19:18:01,282] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 5
    from airflow/fct_script/Authentication_key_retrieval.py import get_schedule
                ^
SyntaxError: invalid syntax
[2023-07-28 19:18:01,286] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:18:01,309] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.043 seconds
[2023-07-28 19:18:11,375] {scheduler_job.py:182} INFO - Started process (PID=154) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:18:11,378] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:18:11,380] {logging_mixin.py:104} INFO - [2023-07-28 19:18:11,380] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:18:11,415] {logging_mixin.py:104} INFO - [2023-07-28 19:18:11,413] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:18:11,418] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:18:11,446] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.076 seconds
[2023-07-28 19:18:41,552] {scheduler_job.py:182} INFO - Started process (PID=156) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:18:41,555] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:18:41,556] {logging_mixin.py:104} INFO - [2023-07-28 19:18:41,556] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:18:41,571] {logging_mixin.py:104} INFO - [2023-07-28 19:18:41,570] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:18:41,573] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:18:41,591] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.044 seconds
[2023-07-28 19:19:11,695] {scheduler_job.py:182} INFO - Started process (PID=158) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:19:11,698] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:19:11,700] {logging_mixin.py:104} INFO - [2023-07-28 19:19:11,700] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:19:11,715] {logging_mixin.py:104} INFO - [2023-07-28 19:19:11,713] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:19:11,717] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:19:11,736] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 19:19:41,840] {scheduler_job.py:182} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:19:41,842] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:19:41,844] {logging_mixin.py:104} INFO - [2023-07-28 19:19:41,844] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:19:41,859] {logging_mixin.py:104} INFO - [2023-07-28 19:19:41,857] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:19:41,862] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:19:41,881] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 19:20:11,987] {scheduler_job.py:182} INFO - Started process (PID=162) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:20:11,991] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:20:11,992] {logging_mixin.py:104} INFO - [2023-07-28 19:20:11,992] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:20:12,008] {logging_mixin.py:104} INFO - [2023-07-28 19:20:12,006] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:20:12,010] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:20:12,030] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:20:42,189] {scheduler_job.py:182} INFO - Started process (PID=164) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:20:42,192] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:20:42,194] {logging_mixin.py:104} INFO - [2023-07-28 19:20:42,194] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:20:42,209] {logging_mixin.py:104} INFO - [2023-07-28 19:20:42,207] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:20:42,212] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:20:42,231] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:21:12,337] {scheduler_job.py:182} INFO - Started process (PID=166) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:21:12,340] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:21:12,342] {logging_mixin.py:104} INFO - [2023-07-28 19:21:12,342] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:21:12,357] {logging_mixin.py:104} INFO - [2023-07-28 19:21:12,355] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:21:12,360] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:21:12,381] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:21:42,481] {scheduler_job.py:182} INFO - Started process (PID=168) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:21:42,485] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:21:42,487] {logging_mixin.py:104} INFO - [2023-07-28 19:21:42,487] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:21:42,502] {logging_mixin.py:104} INFO - [2023-07-28 19:21:42,500] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:21:42,504] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:21:42,524] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:22:12,622] {scheduler_job.py:182} INFO - Started process (PID=170) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:22:12,625] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:22:12,627] {logging_mixin.py:104} INFO - [2023-07-28 19:22:12,627] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:22:12,642] {logging_mixin.py:104} INFO - [2023-07-28 19:22:12,639] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:22:12,644] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:22:12,664] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:22:42,767] {scheduler_job.py:182} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:22:42,769] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:22:42,771] {logging_mixin.py:104} INFO - [2023-07-28 19:22:42,771] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:22:42,786] {logging_mixin.py:104} INFO - [2023-07-28 19:22:42,785] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:22:42,790] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:22:42,810] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:23:12,924] {scheduler_job.py:182} INFO - Started process (PID=174) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:23:12,927] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:23:12,928] {logging_mixin.py:104} INFO - [2023-07-28 19:23:12,928] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:23:12,944] {logging_mixin.py:104} INFO - [2023-07-28 19:23:12,942] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:23:12,947] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:23:12,966] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:23:43,070] {scheduler_job.py:182} INFO - Started process (PID=176) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:23:43,073] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:23:43,075] {logging_mixin.py:104} INFO - [2023-07-28 19:23:43,075] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:23:43,090] {logging_mixin.py:104} INFO - [2023-07-28 19:23:43,088] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:23:43,093] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:23:43,113] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:24:13,217] {scheduler_job.py:182} INFO - Started process (PID=178) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:24:13,220] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:24:13,221] {logging_mixin.py:104} INFO - [2023-07-28 19:24:13,221] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:24:13,237] {logging_mixin.py:104} INFO - [2023-07-28 19:24:13,235] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:24:13,241] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:24:13,261] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:24:43,411] {scheduler_job.py:182} INFO - Started process (PID=180) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:24:43,414] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:24:43,417] {logging_mixin.py:104} INFO - [2023-07-28 19:24:43,417] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:24:43,433] {logging_mixin.py:104} INFO - [2023-07-28 19:24:43,431] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:24:43,435] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:24:43,456] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 19:25:13,560] {scheduler_job.py:182} INFO - Started process (PID=182) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:25:13,563] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:25:13,565] {logging_mixin.py:104} INFO - [2023-07-28 19:25:13,564] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:25:13,580] {logging_mixin.py:104} INFO - [2023-07-28 19:25:13,578] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:25:13,583] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:25:13,603] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:25:43,756] {scheduler_job.py:182} INFO - Started process (PID=184) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:25:43,758] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:25:43,760] {logging_mixin.py:104} INFO - [2023-07-28 19:25:43,760] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:25:43,776] {logging_mixin.py:104} INFO - [2023-07-28 19:25:43,773] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:25:43,779] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:25:43,799] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:26:13,895] {scheduler_job.py:182} INFO - Started process (PID=186) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:26:13,898] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:26:13,900] {logging_mixin.py:104} INFO - [2023-07-28 19:26:13,900] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:26:13,914] {logging_mixin.py:104} INFO - [2023-07-28 19:26:13,913] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:26:13,916] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:26:13,935] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.044 seconds
[2023-07-28 19:26:44,037] {scheduler_job.py:182} INFO - Started process (PID=188) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:26:44,039] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:26:44,041] {logging_mixin.py:104} INFO - [2023-07-28 19:26:44,041] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:26:44,064] {logging_mixin.py:104} INFO - [2023-07-28 19:26:44,060] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:26:44,067] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:26:44,092] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.059 seconds
[2023-07-28 19:27:14,246] {scheduler_job.py:182} INFO - Started process (PID=190) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:27:14,248] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:27:14,250] {logging_mixin.py:104} INFO - [2023-07-28 19:27:14,250] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:27:14,266] {logging_mixin.py:104} INFO - [2023-07-28 19:27:14,264] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:27:14,269] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:27:14,289] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:27:44,388] {scheduler_job.py:182} INFO - Started process (PID=192) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:27:44,391] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:27:44,392] {logging_mixin.py:104} INFO - [2023-07-28 19:27:44,392] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:27:44,405] {logging_mixin.py:104} INFO - [2023-07-28 19:27:44,403] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:27:44,406] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:27:44,423] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.039 seconds
[2023-07-28 19:28:14,553] {scheduler_job.py:182} INFO - Started process (PID=194) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:28:14,555] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:28:14,557] {logging_mixin.py:104} INFO - [2023-07-28 19:28:14,557] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:28:14,572] {logging_mixin.py:104} INFO - [2023-07-28 19:28:14,570] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:28:14,575] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:28:14,595] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:28:44,702] {scheduler_job.py:182} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:28:44,705] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:28:44,706] {logging_mixin.py:104} INFO - [2023-07-28 19:28:44,706] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:28:44,723] {logging_mixin.py:104} INFO - [2023-07-28 19:28:44,720] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:28:44,726] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:28:44,745] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.049 seconds
[2023-07-28 19:29:14,856] {scheduler_job.py:182} INFO - Started process (PID=198) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:29:14,859] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:29:14,860] {logging_mixin.py:104} INFO - [2023-07-28 19:29:14,860] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:29:14,876] {logging_mixin.py:104} INFO - [2023-07-28 19:29:14,873] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:29:14,878] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:29:14,897] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:29:45,000] {scheduler_job.py:182} INFO - Started process (PID=200) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:29:45,003] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:29:45,005] {logging_mixin.py:104} INFO - [2023-07-28 19:29:45,005] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:29:45,021] {logging_mixin.py:104} INFO - [2023-07-28 19:29:45,019] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:29:45,023] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:29:45,044] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.049 seconds
[2023-07-28 19:30:15,157] {scheduler_job.py:182} INFO - Started process (PID=202) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:30:15,160] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:30:15,161] {logging_mixin.py:104} INFO - [2023-07-28 19:30:15,161] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:30:15,177] {logging_mixin.py:104} INFO - [2023-07-28 19:30:15,175] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:30:15,180] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:30:15,200] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:30:45,355] {scheduler_job.py:182} INFO - Started process (PID=204) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:30:45,358] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:30:45,359] {logging_mixin.py:104} INFO - [2023-07-28 19:30:45,359] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:30:45,375] {logging_mixin.py:104} INFO - [2023-07-28 19:30:45,372] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:30:45,377] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:30:45,397] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:31:15,486] {scheduler_job.py:182} INFO - Started process (PID=206) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:31:15,489] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:31:15,491] {logging_mixin.py:104} INFO - [2023-07-28 19:31:15,491] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:31:15,506] {logging_mixin.py:104} INFO - [2023-07-28 19:31:15,504] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:31:15,508] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:31:15,527] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.045 seconds
[2023-07-28 19:31:45,628] {scheduler_job.py:182} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:31:45,630] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:31:45,632] {logging_mixin.py:104} INFO - [2023-07-28 19:31:45,632] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:31:45,648] {logging_mixin.py:104} INFO - [2023-07-28 19:31:45,646] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:31:45,651] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:31:45,671] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:32:15,774] {scheduler_job.py:182} INFO - Started process (PID=210) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:32:15,776] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:32:15,778] {logging_mixin.py:104} INFO - [2023-07-28 19:32:15,778] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:32:15,791] {logging_mixin.py:104} INFO - [2023-07-28 19:32:15,789] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:32:15,793] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:32:15,815] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 19:32:45,913] {scheduler_job.py:182} INFO - Started process (PID=212) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:32:45,915] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:32:45,917] {logging_mixin.py:104} INFO - [2023-07-28 19:32:45,917] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:32:45,932] {logging_mixin.py:104} INFO - [2023-07-28 19:32:45,930] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:32:45,935] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:32:45,954] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 19:33:16,074] {scheduler_job.py:182} INFO - Started process (PID=214) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:33:16,077] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:33:16,079] {logging_mixin.py:104} INFO - [2023-07-28 19:33:16,079] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:33:16,094] {logging_mixin.py:104} INFO - [2023-07-28 19:33:16,092] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:33:16,096] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:33:16,116] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:33:46,217] {scheduler_job.py:182} INFO - Started process (PID=216) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:33:46,220] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:33:46,221] {logging_mixin.py:104} INFO - [2023-07-28 19:33:46,221] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:33:46,236] {logging_mixin.py:104} INFO - [2023-07-28 19:33:46,234] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:33:46,238] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:33:46,258] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 19:34:16,361] {scheduler_job.py:182} INFO - Started process (PID=218) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:34:16,364] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:34:16,365] {logging_mixin.py:104} INFO - [2023-07-28 19:34:16,365] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:34:16,381] {logging_mixin.py:104} INFO - [2023-07-28 19:34:16,379] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:34:16,383] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:34:16,403] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:34:46,509] {scheduler_job.py:182} INFO - Started process (PID=220) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:34:46,512] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:34:46,514] {logging_mixin.py:104} INFO - [2023-07-28 19:34:46,514] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:34:46,530] {logging_mixin.py:104} INFO - [2023-07-28 19:34:46,528] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:34:46,533] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:34:46,552] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:35:16,657] {scheduler_job.py:182} INFO - Started process (PID=222) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:35:16,660] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:35:16,662] {logging_mixin.py:104} INFO - [2023-07-28 19:35:16,662] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:35:16,678] {logging_mixin.py:104} INFO - [2023-07-28 19:35:16,676] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:35:16,680] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:35:16,702] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.049 seconds
[2023-07-28 19:35:46,795] {scheduler_job.py:182} INFO - Started process (PID=224) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:35:46,798] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:35:46,800] {logging_mixin.py:104} INFO - [2023-07-28 19:35:46,800] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:35:46,818] {logging_mixin.py:104} INFO - [2023-07-28 19:35:46,815] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:35:46,820] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:35:46,841] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.052 seconds
[2023-07-28 19:36:16,939] {scheduler_job.py:182} INFO - Started process (PID=226) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:36:16,944] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:36:16,946] {logging_mixin.py:104} INFO - [2023-07-28 19:36:16,946] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:36:16,962] {logging_mixin.py:104} INFO - [2023-07-28 19:36:16,960] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:36:16,965] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:36:16,986] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.052 seconds
[2023-07-28 19:36:47,123] {scheduler_job.py:182} INFO - Started process (PID=228) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:36:47,126] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:36:47,128] {logging_mixin.py:104} INFO - [2023-07-28 19:36:47,128] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:36:47,143] {logging_mixin.py:104} INFO - [2023-07-28 19:36:47,140] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:36:47,145] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:36:47,167] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.049 seconds
[2023-07-28 19:37:17,277] {scheduler_job.py:182} INFO - Started process (PID=230) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:37:17,280] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:37:17,281] {logging_mixin.py:104} INFO - [2023-07-28 19:37:17,281] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:37:17,298] {logging_mixin.py:104} INFO - [2023-07-28 19:37:17,296] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:37:17,301] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:37:17,320] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:37:47,419] {scheduler_job.py:182} INFO - Started process (PID=232) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:37:47,422] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:37:47,424] {logging_mixin.py:104} INFO - [2023-07-28 19:37:47,424] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:37:47,440] {logging_mixin.py:104} INFO - [2023-07-28 19:37:47,437] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:37:47,442] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:37:47,462] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:38:17,641] {scheduler_job.py:182} INFO - Started process (PID=234) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:38:17,644] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:38:17,645] {logging_mixin.py:104} INFO - [2023-07-28 19:38:17,645] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:38:17,661] {logging_mixin.py:104} INFO - [2023-07-28 19:38:17,659] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:38:17,664] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:38:17,684] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:38:47,795] {scheduler_job.py:182} INFO - Started process (PID=236) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:38:47,797] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:38:47,799] {logging_mixin.py:104} INFO - [2023-07-28 19:38:47,799] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:38:47,814] {logging_mixin.py:104} INFO - [2023-07-28 19:38:47,812] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:38:47,816] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:38:47,836] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 19:39:17,935] {scheduler_job.py:182} INFO - Started process (PID=238) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:39:17,938] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:39:17,940] {logging_mixin.py:104} INFO - [2023-07-28 19:39:17,940] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:39:17,955] {logging_mixin.py:104} INFO - [2023-07-28 19:39:17,953] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:39:17,957] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:39:17,978] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:39:48,079] {scheduler_job.py:182} INFO - Started process (PID=240) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:39:48,082] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:39:48,083] {logging_mixin.py:104} INFO - [2023-07-28 19:39:48,083] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:39:48,098] {logging_mixin.py:104} INFO - [2023-07-28 19:39:48,096] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:39:48,101] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:39:48,120] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 19:40:18,270] {scheduler_job.py:182} INFO - Started process (PID=242) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:40:18,272] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:40:18,274] {logging_mixin.py:104} INFO - [2023-07-28 19:40:18,274] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:40:18,289] {logging_mixin.py:104} INFO - [2023-07-28 19:40:18,287] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:40:18,292] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:40:18,313] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:40:48,423] {scheduler_job.py:182} INFO - Started process (PID=244) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:40:48,425] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:40:48,426] {logging_mixin.py:104} INFO - [2023-07-28 19:40:48,426] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:40:48,441] {logging_mixin.py:104} INFO - [2023-07-28 19:40:48,439] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:40:48,444] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:40:48,463] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 19:41:18,619] {scheduler_job.py:182} INFO - Started process (PID=246) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:41:18,621] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:41:18,623] {logging_mixin.py:104} INFO - [2023-07-28 19:41:18,623] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:41:18,638] {logging_mixin.py:104} INFO - [2023-07-28 19:41:18,636] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:41:18,640] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:41:18,660] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.046 seconds
[2023-07-28 19:41:48,764] {scheduler_job.py:182} INFO - Started process (PID=248) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:41:48,767] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:41:48,768] {logging_mixin.py:104} INFO - [2023-07-28 19:41:48,768] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:41:48,781] {logging_mixin.py:104} INFO - [2023-07-28 19:41:48,779] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:41:48,784] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:41:48,801] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.041 seconds
[2023-07-28 19:42:18,901] {scheduler_job.py:182} INFO - Started process (PID=250) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:42:18,905] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:42:18,906] {logging_mixin.py:104} INFO - [2023-07-28 19:42:18,906] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:42:18,918] {logging_mixin.py:104} INFO - [2023-07-28 19:42:18,916] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:42:18,920] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:42:18,937] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.040 seconds
[2023-07-28 19:42:49,064] {scheduler_job.py:182} INFO - Started process (PID=252) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:42:49,066] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:42:49,068] {logging_mixin.py:104} INFO - [2023-07-28 19:42:49,068] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:42:49,084] {logging_mixin.py:104} INFO - [2023-07-28 19:42:49,082] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:42:49,087] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:42:49,107] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:43:19,236] {scheduler_job.py:182} INFO - Started process (PID=254) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:43:19,239] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:43:19,241] {logging_mixin.py:104} INFO - [2023-07-28 19:43:19,241] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:43:19,256] {logging_mixin.py:104} INFO - [2023-07-28 19:43:19,254] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:43:19,260] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:43:19,279] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:43:49,383] {scheduler_job.py:182} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:43:49,386] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:43:49,388] {logging_mixin.py:104} INFO - [2023-07-28 19:43:49,388] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:43:49,404] {logging_mixin.py:104} INFO - [2023-07-28 19:43:49,402] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:43:49,406] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:43:49,425] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.047 seconds
[2023-07-28 19:44:19,572] {scheduler_job.py:182} INFO - Started process (PID=258) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:44:19,575] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:44:19,576] {logging_mixin.py:104} INFO - [2023-07-28 19:44:19,576] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:44:19,589] {logging_mixin.py:104} INFO - [2023-07-28 19:44:19,587] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:44:19,591] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:44:19,607] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.039 seconds
[2023-07-28 19:44:49,709] {scheduler_job.py:182} INFO - Started process (PID=260) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:44:49,712] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:44:49,714] {logging_mixin.py:104} INFO - [2023-07-28 19:44:49,714] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:44:49,733] {logging_mixin.py:104} INFO - [2023-07-28 19:44:49,731] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:44:49,736] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:44:49,752] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.048 seconds
[2023-07-28 19:45:19,848] {scheduler_job.py:182} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:45:19,851] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:45:19,853] {logging_mixin.py:104} INFO - [2023-07-28 19:45:19,853] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:45:19,865] {logging_mixin.py:104} INFO - [2023-07-28 19:45:19,863] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:45:19,868] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:45:19,887] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.042 seconds
[2023-07-28 19:45:50,032] {scheduler_job.py:182} INFO - Started process (PID=264) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:45:50,035] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:45:50,036] {logging_mixin.py:104} INFO - [2023-07-28 19:45:50,036] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:45:50,050] {logging_mixin.py:104} INFO - [2023-07-28 19:45:50,048] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:45:50,052] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:45:50,070] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.043 seconds
[2023-07-28 19:46:20,172] {scheduler_job.py:182} INFO - Started process (PID=266) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:46:20,174] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:46:20,175] {logging_mixin.py:104} INFO - [2023-07-28 19:46:20,175] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:46:20,188] {logging_mixin.py:104} INFO - [2023-07-28 19:46:20,186] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:46:20,191] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:46:20,208] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.040 seconds
[2023-07-28 19:46:50,310] {scheduler_job.py:182} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:46:50,312] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:46:50,313] {logging_mixin.py:104} INFO - [2023-07-28 19:46:50,313] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:46:50,326] {logging_mixin.py:104} INFO - [2023-07-28 19:46:50,324] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:46:50,328] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:46:50,346] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.041 seconds
[2023-07-28 19:50:25,375] {scheduler_job.py:182} INFO - Started process (PID=270) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:50:25,381] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:50:25,385] {logging_mixin.py:104} INFO - [2023-07-28 19:50:25,385] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:50:25,414] {logging_mixin.py:104} INFO - [2023-07-28 19:50:25,412] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:50:25,419] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:50:25,460] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.120 seconds
[2023-07-28 19:50:55,725] {scheduler_job.py:182} INFO - Started process (PID=272) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:50:55,744] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:50:55,753] {logging_mixin.py:104} INFO - [2023-07-28 19:50:55,752] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:50:55,835] {logging_mixin.py:104} INFO - [2023-07-28 19:50:55,825] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:50:55,851] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:50:55,978] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.283 seconds
[2023-07-28 19:55:25,717] {scheduler_job.py:182} INFO - Started process (PID=275) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:55:25,719] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:55:25,721] {logging_mixin.py:104} INFO - [2023-07-28 19:55:25,721] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:55:25,740] {logging_mixin.py:104} INFO - [2023-07-28 19:55:25,738] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:55:25,743] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:55:25,764] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.055 seconds
[2023-07-28 19:55:56,249] {scheduler_job.py:182} INFO - Started process (PID=277) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:55:56,260] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 19:55:56,268] {logging_mixin.py:104} INFO - [2023-07-28 19:55:56,267] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:55:56,345] {logging_mixin.py:104} INFO - [2023-07-28 19:55:56,337] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 19:55:56,356] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 19:55:56,460] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.230 seconds
[2023-07-28 20:00:25,339] {scheduler_job.py:182} INFO - Started process (PID=279) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:00:25,344] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:00:25,347] {logging_mixin.py:104} INFO - [2023-07-28 20:00:25,346] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:00:25,377] {logging_mixin.py:104} INFO - [2023-07-28 20:00:25,371] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:00:25,388] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:00:25,454] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.121 seconds
[2023-07-28 20:00:25,785] {scheduler_job.py:182} INFO - Started process (PID=281) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:00:25,788] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:00:25,790] {logging_mixin.py:104} INFO - [2023-07-28 20:00:25,790] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:00:25,806] {logging_mixin.py:104} INFO - [2023-07-28 20:00:25,803] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:00:25,809] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:00:25,831] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.051 seconds
[2023-07-28 20:00:56,190] {scheduler_job.py:182} INFO - Started process (PID=283) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:00:56,215] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:00:56,225] {logging_mixin.py:104} INFO - [2023-07-28 20:00:56,224] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:00:56,329] {logging_mixin.py:104} INFO - [2023-07-28 20:00:56,317] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:00:56,341] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:00:56,490] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.343 seconds
[2023-07-28 20:05:25,730] {scheduler_job.py:182} INFO - Started process (PID=286) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:05:25,733] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:05:25,735] {logging_mixin.py:104} INFO - [2023-07-28 20:05:25,735] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:05:25,753] {logging_mixin.py:104} INFO - [2023-07-28 20:05:25,751] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:05:25,757] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:05:25,781] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.056 seconds
[2023-07-28 20:05:56,143] {scheduler_job.py:182} INFO - Started process (PID=288) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:05:56,156] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:05:56,166] {logging_mixin.py:104} INFO - [2023-07-28 20:05:56,165] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:05:56,258] {logging_mixin.py:104} INFO - [2023-07-28 20:05:56,248] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:05:56,269] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:05:56,457] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.337 seconds
[2023-07-28 20:10:25,176] {scheduler_job.py:182} INFO - Started process (PID=290) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:10:25,181] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:10:25,185] {logging_mixin.py:104} INFO - [2023-07-28 20:10:25,185] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:10:25,213] {logging_mixin.py:104} INFO - [2023-07-28 20:10:25,210] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:10:25,217] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:10:25,265] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.107 seconds
[2023-07-28 20:10:55,782] {scheduler_job.py:182} INFO - Started process (PID=292) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:10:55,792] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:10:55,801] {logging_mixin.py:104} INFO - [2023-07-28 20:10:55,800] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:10:55,877] {logging_mixin.py:104} INFO - [2023-07-28 20:10:55,867] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:10:55,887] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:10:56,018] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.256 seconds
[2023-07-28 20:13:39,210] {scheduler_job.py:182} INFO - Started process (PID=294) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:13:39,218] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:13:39,223] {logging_mixin.py:104} INFO - [2023-07-28 20:13:39,223] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:13:39,238] {logging_mixin.py:104} INFO - [2023-07-28 20:13:39,236] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:13:39,241] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:13:39,440] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.236 seconds
[2023-07-28 20:14:09,618] {scheduler_job.py:182} INFO - Started process (PID=296) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:14:09,621] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:14:09,622] {logging_mixin.py:104} INFO - [2023-07-28 20:14:09,622] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:14:09,638] {logging_mixin.py:104} INFO - [2023-07-28 20:14:09,636] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:14:09,640] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:14:09,661] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 20:14:39,808] {scheduler_job.py:182} INFO - Started process (PID=298) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:14:39,810] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:14:39,813] {logging_mixin.py:104} INFO - [2023-07-28 20:14:39,813] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:14:39,830] {logging_mixin.py:104} INFO - [2023-07-28 20:14:39,828] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:14:39,832] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:14:39,853] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.050 seconds
[2023-07-28 20:15:09,997] {scheduler_job.py:182} INFO - Started process (PID=300) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:15:10,000] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:15:10,002] {logging_mixin.py:104} INFO - [2023-07-28 20:15:10,002] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:15:10,019] {logging_mixin.py:104} INFO - [2023-07-28 20:15:10,017] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:15:10,021] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:15:10,055] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.063 seconds
[2023-07-28 20:15:40,215] {scheduler_job.py:182} INFO - Started process (PID=302) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:15:40,218] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:15:40,220] {logging_mixin.py:104} INFO - [2023-07-28 20:15:40,219] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:15:40,238] {logging_mixin.py:104} INFO - [2023-07-28 20:15:40,236] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:15:40,241] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:15:40,282] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.072 seconds
[2023-07-28 20:16:10,420] {scheduler_job.py:182} INFO - Started process (PID=304) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:16:10,426] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:16:10,427] {logging_mixin.py:104} INFO - [2023-07-28 20:16:10,427] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:16:10,444] {logging_mixin.py:104} INFO - [2023-07-28 20:16:10,442] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:16:10,447] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:16:10,470] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.055 seconds
[2023-07-28 20:16:40,621] {scheduler_job.py:182} INFO - Started process (PID=306) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:16:40,624] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:16:40,626] {logging_mixin.py:104} INFO - [2023-07-28 20:16:40,626] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:16:40,643] {logging_mixin.py:104} INFO - [2023-07-28 20:16:40,641] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:16:40,646] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:16:40,676] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.060 seconds
[2023-07-28 20:17:10,829] {scheduler_job.py:182} INFO - Started process (PID=308) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:17:10,831] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:17:10,833] {logging_mixin.py:104} INFO - [2023-07-28 20:17:10,833] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:17:10,848] {logging_mixin.py:104} INFO - [2023-07-28 20:17:10,846] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:17:10,851] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:17:10,880] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.055 seconds
[2023-07-28 20:17:41,031] {scheduler_job.py:182} INFO - Started process (PID=310) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:17:41,034] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:17:41,036] {logging_mixin.py:104} INFO - [2023-07-28 20:17:41,036] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:17:41,053] {logging_mixin.py:104} INFO - [2023-07-28 20:17:41,051] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:17:41,055] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:17:41,079] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.052 seconds
[2023-07-28 20:18:11,223] {scheduler_job.py:182} INFO - Started process (PID=312) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:18:11,226] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:18:11,227] {logging_mixin.py:104} INFO - [2023-07-28 20:18:11,227] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:18:11,243] {logging_mixin.py:104} INFO - [2023-07-28 20:18:11,241] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:18:11,247] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:18:11,270] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.051 seconds
[2023-07-28 20:18:41,418] {scheduler_job.py:182} INFO - Started process (PID=314) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:18:41,420] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:18:41,423] {logging_mixin.py:104} INFO - [2023-07-28 20:18:41,423] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:18:41,468] {logging_mixin.py:104} INFO - [2023-07-28 20:18:41,462] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:18:41,473] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:18:41,502] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.090 seconds
[2023-07-28 20:19:11,647] {scheduler_job.py:182} INFO - Started process (PID=316) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:19:11,649] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:19:11,651] {logging_mixin.py:104} INFO - [2023-07-28 20:19:11,651] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:19:11,668] {logging_mixin.py:104} INFO - [2023-07-28 20:19:11,665] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:19:11,672] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:19:11,693] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.051 seconds
[2023-07-28 20:19:41,835] {scheduler_job.py:182} INFO - Started process (PID=318) to work on /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:19:41,838] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/dag_extract_train.py for tasks to queue
[2023-07-28 20:19:41,841] {logging_mixin.py:104} INFO - [2023-07-28 20:19:41,840] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:19:41,856] {logging_mixin.py:104} INFO - [2023-07-28 20:19:41,854] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/dag_extract_train.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_extract_train.py", line 6, in <module>
    from preprocessing_function.data_preprocessor_fct import preprocess_data
ModuleNotFoundError: No module named 'preprocessing_function'
[2023-07-28 20:19:41,859] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_extract_train.py
[2023-07-28 20:19:41,896] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/dag_extract_train.py took 0.067 seconds
